version: '2.2'

services:
  builder:
    image: "docker.tuenti.io/voice-builder:2.1.0"
    volumes:
      - "${PWD}/:/sources"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "WORKDIR=${PWD}"
