version: "3.3"

services:
  mpm-server:
    build:
      context: ../
      dockerfile: local-development/Dockerfile
    image: lifecycle/msteams-private-messages
    container_name: mpm-server
    volumes:
      - ..:/usr/src/app/
    environment:
      - MYSQL_HOST=mpm-db
    depends_on:
      - mpm-db
    ports:
      - ${PORT:-3978}:${PORT:-3978}

  mpm-db:
    image: mysql:5.7
    container_name: mpm-db
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3307:3306"
    volumes:
      - data-storage:/var/lib/mysql

volumes:
  data-storage: {}
