version: "3.3"

services:
  mpm-server:
    build: .
    image: lifecycle/msteams-private-messages
    container_name: mpm-server
    volumes:
      - ${PWD}/..:/usr/src/app/
    environment:
      - MYSQL_HOST=mpm-db
    depends_on:
      - mpm-db
    ports:
      - ${PORT:-3978}:${PORT:-3978}
    expose:
      - ${PORT:-3978}

  mpm-db:
    image: mysql:5.7
    container_name: mpm-db
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
    volumes:
      - data-storage:/var/lib/mysql

volumes:
  data-storage: {}
